
version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.17.0.1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zeek:
    image: thiagosordi/zeek
    network_mode: host
    container_name: zeek
    command: tail -F anything
#    command: zeekctl deploy
    volumes:
      - ./node.cfg:/usr/local/zeek/etc/node.cfg
      - ./local.zeek:/usr/local/zeek/share/zeek/site/local.zeek
      - ./main.zeek:/usr/local/zeek/share/zeek/base/frameworks/logging/main.zeek

  cassandra-n01:
    image: cassandra:latest
    container_name: cassandra-n01
    volumes:
      - n01-volume:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-n01
#     - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2, cassandra-node3

#  cassandra-node2:
#    image: cassandra:latest
#    container_name: node2
#    environment:
#      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
#      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2, cassandra-node3
#
#  cassandra-node3:
#    image: cassandra:latest
#    container_name: node3
#    environment:
#      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
#      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2, cassandra-node3
#
  spark-streaming:
    image: thiagosordi/spark-streaming
    container_name: spark-streaming
    ports:
      - "8080:8080"
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-streaming --webui-port 8080
    volumes:
      - ./spark.py:/spark/spark.py
      - ./cassandra_helper.py:/spark/cassandra_helper.py
#      - ./cassandra.py:/spark/cassandra.py

volumes:
  n01-volume:
