
version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
    - "2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zeek:
    image: thiagosordi/zeek
    network_mode: host
    container_name: zeek
    command: zeekctl deploy
    volumes:
      - ./node.cfg:/usr/local/zeek/etc/node.cfg
      - ./local.zeek:/usr/local/zeek/share/zeek/site/local.zeek

  cassandra-node1:
    image: bitnami/cassandra:latest
    container_name: node1
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2, cassandra-node3

  cassandra-node2:
    image: bitnami/cassandra:latest
    container_name: node2
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2, cassandra-node3

  cassandra-node3:
    image: bitnami/cassandra:latest
    container_name: node3
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2, cassandra-node3

  spark-streaming:
    image: thiagosordi/spark-streaming
    network_mode: host
    container_name: spark-streaming
    
