
version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
    - "2181"

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zeek:
    image: thiagosordi/zeek
    network_mode: host
    container_name: zeek
    command: tail -F anything
    volumes:
      - /home/jvlima/bigdata:/dados
      - ./node.cfg:/usr/local/zeek/etc/node.cfg
      - ./Zeek-docker/local.zeek:/usr/local/zeek/share/zeek/site/local.zeek

    #  hbase:
    #    image: harisekhon/hbase
    #    container_name: hbase

    #  spark-streaming:
    #    image: thiagosordi/spark-streaming
    #    network_mode: host
    #    container_name: spark-streaming
    
